### ISSUE TITLE
Example SPARQL queries in The Semantic Web & Linked Data should return data

### ISSUE THREAD

**Issue by crtahlin** [RubenVerborgh/WebFundamentals#60]
I am not 100% sure if it is a "bug" or desired behavior, but it seems strange that the example query would return no results (see screenshot):

![image](https://user-images.githubusercontent.com/1554520/49067093-51813700-f223-11e8-8ef9-ebc7cc43eee8.png)

Also, the previous two query examples return either no results or just the schema URIs. Seems strange, since examples should return something and also the query seems like there should be hits.

Although, "manually" checking
http://fragments.dbpedia.org/2016-04/en?subject=&predicate=&object=http%3A%2F%2Fdbpedia.org%2Fresource%2FPablo_Picaso
There is only one relation pointing to Pablo Picaso (and not being influencedBy), so I guess the results are as expected?

Anyway, I would suggest the examples be such, that they return data; that would be more informative for studying, IMO.

**Comment by crtahlin** [comment]
Also, the query on the next slide returns an error, so I am pretty convinced that something broke (see screenshot):

![image](https://user-images.githubusercontent.com/1554520/49067834-66f76080-f225-11e8-8957-3a5cc35e482a.png)

For reference, this is the slide: https://rubenverborgh.github.io/WebFundamentals/semantic-web/#sparql-describe-client

**Comment by RubenVerborgh** [comment]
@crtahlin I know this is _very_ confusing, but the problem is that you are loading the https: version and not the http:// version.

Since the fragments of this query are on http://, they get blocked if you try to query them from https://. Hence you don't get the results.

Fixed when you go to http://rubenverborgh.github.io/WebFundamentals/semantic-web/#sparql-ask-client

This is a security limitation of Web browsers. This can be mitigated for this specific case if fragments.dbpedia.org moves to https://, but in general one cannot query http:// interfaces from an https:// page.

**Comment by crtahlin** [comment]
@RubenVerborgh Ok, thank you for the answer (verified, it does off course work with http://).
I guess will close the issue/question.

As a note I would suggest adding some note/warning somewhere in the slides that the connection has to be http://; otherwise you will surely get more reports like these (or some very confused students :). I'm not even sure how my connection got set to https instead of http.

**Comment by RubenVerborgh** [comment]
Indeed, thanks for noticing!
