### ISSUE TITLE
The Web includes non-Internet resources like files and local routers

### ISSUE THREAD

**Issue by royfielding** [RubenVerborgh/WebFundamentals#63]
https://github.com/RubenVerborgh/WebFundamentals/blob/5edaeea4a66d18bd23090bf48f4bf4573982e836/birds-eye-view/index.html#L655

I know this is a minor point, but the Web protocols were specifically designed to encompass the space of Internet resources (accessible to everyone) and private resources (auth required) and local resources (things that are only defined in relation to the local user, like local file URLs and local router identifiers). The Internet itself doesn't work without them, but the Web does, which is why all local wifi services start with a non-encrypted HTTP request to obtain the instructions necessary to use the local network for access to the larger Internet.

BTW, nice slides!

**Comment by RubenVerborgh** [comment]
Thanks! The interesting thing is that I often tell this during class when I'm teaching.
In fact, it happened last week: I showed these slides to the group (and I have builds on, so they see the question "on the Web but not on the Internet" but not yet the answer). One of the students indeed made a remark on local files, intranet, etc.

It's probably a good idea to clarify this on the slide as well, since people outside of my class do not get that extra bit of content.
